### ISSUE TITLE
Extract Home Assistant API code to its own published crate

### ISSUE THREAD

**Issue by kylepotts** [selfhostedshow/halcyon#16]
To keep some of the project clean, we should move the home assistant api code to an external crate for others to use if they want to.

**Comment by ironicbadger** [comment]
Not knowing fully what a crate is, does this effectively make the API integration code into a reusable component? If so, that sounds great.

**Comment by BCNelson** [comment]
Done [Selfhostedshow/ha_api](https://github.com/selfhostedshow/ha_api)

**Comment by RealOrangeOne** [comment]
There already appears to be a HA API library on crates.io: https://crates.io/search?q=home-assistant

I'd be interested in either trying to reuse that library, or potentially upstream our changes to it.

**Comment by BCNelson** [comment]
That one has been unmaintained for several years and the library does not support the mobile app api. I agree thought upstreaming would be better. I looked for the maintainers contact info but could not find it. Maybe mentioning them will get there attention @kpcyrd

**Comment by kpcyrd** [comment]
I don't see myself maintaining my old crate in the future, but I would be fine with adding new maintainers to the repo and have the codebase replaced. :)

**Comment by BCNelson** [comment]
@kpcyrd Perfect, thank you. As I see it we have two options.
1. As you suggested add some people as maintainers on the repo and have the code base replaced.
2. Transfer the crates.io namespace to us and we create the repo under the selfhostedshow organization

Ether works for us but the second is ideal if you aren't planning on getting involved.

**Comment by kpcyrd** [comment]
If possible I'd prefer transferring the crates.io namespace to somebody involved with the home-assistant org who would then add you as additional owners. That way home-assistant is able to add new maintainers if the crate stales for whatever reason. :)

**Comment by BCNelson** [comment]
Any ideas on who we should contact in the Home Assistant Org?

**Comment by kpcyrd** [comment]
I've pinged them on twitter, in the meantime I can already add you as owner, I'd just prefer to have somebody from homeassistant as a co-owner before I remove myself from the namespace.

**Comment by kpcyrd** [comment]
I've checked and they don't seem concerned, what are your crates.io usernames?

**Comment by BCNelson** [comment]
bcnelson
