### ISSUE TITLE
What GUI toolkit do we want to use? 

### ISSUE THREAD

**Issue by kprestel** [selfhostedshow/halcyon#18]
I figure at some point we will want to add a GUI to this. Does anyone have any suggestions for which toolkit/crate we should use?

**Comment by RealOrangeOne** [comment]
My strong recommendation would be not to have a GUI.

Keeping everything config-file driven is a small hurdle for use, but given to use HA you need at least a fundemental understanding of YAML, it's not a big ask. It also makes it easy to transfer between machines, version control, and do fun things around templating, much like HA does.

Maintaining a GUI requires significantly more code and complexity and scope for bugs.

I'd be open to a `halcyon config` command which opens the config file in `$EDITOR` though as a middleground.

**Comment by kprestel** [comment]
I agree, that makes sense to me. 

We can add a GUI later on if we want to.
